### ISSUE TITLE
Error running the example code

### ISSUE THREAD

**Issue by phuongquan** [miracum/dqa-dqastats#1]
Hi, I downloaded DQAstats from CRAN last week and get this error when running the example code from the Readme:

Version of 'DIZutils': 0.0.15
Version of 'DQAstats': 0.2.6
INFO [2022-03-11 14:41:36] using future::plan("multisession") (d142855e3c)
Error in makeNode(workers[[ii]], port = port, ..., rank = ii, action = "options",  : 
  could not find function "makeNode"

Thanks,
Phuong

**Comment by kapsner** [comment]
Hi @phuongquan,

we have identified the error and it was fixed with commit b8a4e32e29d78b998e2c93f6602fa7c0167c2af6

So you could either try to install the package from the development branch: `remotes::install_github("miradum/dqa-dqastats", ref = "development")`, or alternatively, you could try to run the `dqa()`-function with the argument `parallel=FALSE` (which switches off the parallelization).

**Comment by phuongquan** [comment]
Thanks, setting parallel=FALSE worked for me.
